[package]
name = "bevy_twin_stick"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version = "0.11"} # Find a way to disable this for release
# bevy_rapier2d = {version = "0.19.0", features = ["simd-stable", "debug-render", "parallel"]}
bevy_rapier2d = "0.22"
bevy_mod_transform2d = { git = "https://github.com/Zellenon/bevy_mod_transform2d.git", features = ["bevy_rapier2d"] }
bevy-inspector-egui = "0.20"
bevy_turborand = "0.6"

bevy_prototype_lyon = {version = "0.9"}
